### ISSUE TITLE
Regression results comparison

### ISSUE THREAD

**Issue by rachelicr** [instituteofcancerresearch/he-class-pipeline#22]
Create a way to run a full test through on the test data and compare every step against the regression data

**Comment by rachelicr** [comment]
Comparing image files in python from stackoverflow: https://stackoverflow.com/questions/58099235/how-to-compare-two-image-files-contents-in-python

**Comment by stacyrse** [comment]
Comparing images script for pipelines A-C has been written but not pushed to the repo

**Comment by rachelicr** [comment]
Add as a function with 2 params in a utils directory.

**Comment by stacyrse** [comment]
Branch fix_issue_22 has been merged
